blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('', views.index),
    # path('<int:pk>/', views.single_post_page),

    # /blog/
    path('', views.PostList.as_view(), name='post_list'),
    # /blog/1/
    path('<int:pk>/', views.PostDetail.as_view(), name='post_detail'),

    # /blog/category/{self.slug}/
    # /blog/category/파이썬
    path('category/<str:slug>/', views.category_page, name='category_filter'),

    path('tag/<str:slug>/', views.tag_page, name='tag_filter'),

    path('create_post/', views.PostCreate.as_view(), name='create_post'),

    path('search/<str:q>/', views.PostSearch.as_view()),

    # /blog/update_post/페이지
    path('update_post/<int:pk>/', views.PostUpdate.as_view(), name='update_post'),

    path('<int:pk>/new_comment/', views.new_comment),

    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),

    path('delete_comment/<int:pk>/', views.delete_comment),
]

doit_django_prj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('', include('single_pages.urls')),
    path('summernote/', include('django_summernote.urls')),
    # all-auth path
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
import os


class Tag(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return f'/blog/tag/{self.slug}/'


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return f'/blog/category/{self.slug}/'
    
    # class Meta:
    #     verbose_name_plural = 'Categories'

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    hook_text = models.CharField(max_length=100, blank=True)
    content = models.TextField()


    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d', blank=True)
    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return f'[{self.pk}]{self.title} :: {self.author}'
    
    def get_absolute_url(self):
        return f'/blog/{self.pk}/'
    
    def get_file_name(self):
        return os.path.basename(self.file_upload.name)
    
    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]
    
# 댓글기능
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author}::{self.content}'
    
    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

blog/forms.py
# forms.py

from django_summernote.widgets import SummernoteWidget
from django import forms
from .models import Post
from .models import Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category']
        widgets = {
            'content': SummernoteWidget(),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

blog/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify
from django.shortcuts import get_object_or_404
from .models import Post, Category, Tag, Comment
from .forms import PostForm, CommentForm

# Create your views here.
# def index(request):
#     posts = Post.objects.all().order_by('-pk')

#     return render(
#         request,
#         'blog/index.html',
#         {
#           'posts' : posts
#         }
#     )

# superuser 또는 staff만 포스트를 작성할 수 있게 만들기
class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    # fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category']
    form_class = PostForm
    # template_name 생략가능하다(이름을 이렇게 줬기때문에 내부적으로 알아서 읽음)
    template_name = 'blog/post_form.html'

    # 페이지 접근 권한을 부여한다(superuser 또는 staff)
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff
    # 로그인한 사용자가 superuser 또는 staff일때, 동작하게하기
    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            form.instance.author = current_user
            # input 요소에 입력된 값을 가져오기 위한 기능추가(tag)
            response = super(PostCreate, self).form_valid(form)
        
            tags_str = self.request.POST.get('tags_str')
            # tag_str로 받은 값의 쉼표를 세미콜론으로 모두 변경하고, 세미콜론으로 split 해서 리스트형태로 tags_list에 담는다
            if tags_str:
                tags_str = tags_str.strip()

                tags_str = tags_str.replace(',', ';')
                tags_list = tags_str.split(';')
                # 마지막태그에 ;추가시 자동 공백생성오류를 해결하기위한 print()문
                # print(tags_list)
                # ['tag1', 'tag2', '']

                # tags_list의 문자열형태의 리스트 -> Tag모델의 인스턴스로 변환
                for t in tags_list:
                    # 앞뒤 공백 제거
                    t = t.strip()
                    # print(t)

                    # tag가 공백일때는 pass(for문 첫문장으로 이동해서 다음 요소로 수행)
                    if t == "":
                        continue
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)
                    # print(f'tag, is_tag_created : {tag}, {is_tag_created}')

                    # slug 값 생성
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode=True)
                        tag.save()
                    self.object.tags.add(tag)

            return response
        else:
            return redirect('/blog/')


class PostDetail(DetailView): 
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        context['categories'] = Category.objects.all()
        # Post 테이블에서  category 필드를 선택안한 포스트의 갯수
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        context['comment_form'] = CommentForm
        return context



class PostList(ListView):
    model = Post
    ordering = '-pk'
    # 한 페이지당 보여줄 post 갯수 설정
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data()
        context['categories'] = Category.objects.all()
        # Post 테이블에서  category 필드를 선택안한 포스트의 갯수
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        return context

    # post_list.html : class이름_list.html내부적으로 정의가 되어있기 때문에 생략가능
    # 파일명을 위에있는 규칙으로 하지않을경우 명시해줘야함
    # template_name = 'blog/post_list.html'

# def single_post_page(request, pk):
#     post = Post.objects.get(pk=pk)

#     return render(
#         request,
#         'blog/single_post_page.html',
#         {
#           'post': post,
#         }
#     )

# 방법1
# def category_page(request, slug):
#     # 비어있는 딕셔너리 변수 선언
#     context = {}
#     # 선택한 슬러그에 해당하는 Category테이블의 레코드를 가져옴
#     category = Category.objects.get(slug=slug)
#     # post 테이블에서 선택한 category의 레코드만 필터링
#     context['post_list'] = Post.objects.filter(category=category)
#     # Category 테이블의 목록 모두 가져옴
#     context['categories'] = Category.objects.all()
#     # Post 테이블에서  category 필드를 선택안한 포스트의 갯수
#     context['no_category_post_count'] = Post.objects.filter(category=None).count()
#     # 선택한 카테고리의 레코드
#     context['category'] = category
#     # print(context)

#     return render(
#         request,
#         'blog/post_list.html',
#         context
#     )


# 방법2
def category_page(request, slug):
    if slug == 'no_category':
        category = '미분류'
        post_list = Post.objects.filter(category=None)
    else:
        # 선택한 슬러그의 해당하는 Category테이블의 레코드
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)
        # Post 테이블에서 선택한 category의 레코드만 필터링

    context = {
        'post_list': post_list,
        'categories': Category.objects.all(),
        'no_category_post_cnt': Post.objects.filter(category=None).count(),
        'category': category
    }
    # print(context)
    return render(request,'blog/post_list.html', context)


def tag_page(request, slug):
    tag = Tag.objects.get(slug=slug)
    post_list = tag.post_set.all()

    return render(
        request,
        'blog/post_list.html',
        {
            'post_list': post_list,
            'tag' : tag,
            'categories': Category.objects.all(),
            'no_category_post_count': Post.objects.filter(category=None).count(),
        }
    )


class PostSearch(PostList):
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(
            Q(title__contains=q) | Q(tags__name__contains=q)
        ).distinct()
        return post_list
    
    def get_context_data(self, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'

        return context

# post 수정페이지 구현
class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    # fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category', 'tags']
    # summernote로 update form구현
    form_class = PostForm

    template_name = 'blog/post_update_form.html'

    def get_context_data(self, **kwargs):
        context = super(PostUpdate, self).get_context_data()
        if self.object.tags.exists():
            tags_str_list = list()
            for t in self.object.tags.all():
                tags_str_list.append(t.name)
            context['tags_str_default'] = '; '.join(tags_str_list)

        return context
    
    def form_valid(self, form):
        response = super(PostUpdate, self).form_valid(form)
        self.object.tags.clear()

        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str.replace(',', ';')
            tags_list = tags_str.split(';')

            for t in tags_list:
                t = t.strip()
                if t == "":
                    continue
                tag, is_tag_created = Tag.objects.get_or_create(name=t)
                if is_tag_created:
                    tag.slug = slugify(t, allow_unicode=True)
                    tag.save()
                self.object.tags.add(tag)

        return response

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied
        

# 로그인한상태로 댓글쓰기허용
def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)

        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
            else:
                return redirect(post.get_absolute_url())
        else:
            raise PermissionDenied
        
class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied
        
def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

blog/templates/blog/comment_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}Edit Comment - Blog{% endblock %}

{% block main_area %}
<div class="row">

    <!-- Blog entries-->
    <div class="col-lg-12" id="main-area">
        <h1>Edit Comment</h1>
        <hr>
        <div>
            <form method="post" id="comment-form">{% csrf_token %}
                    {{ form | crispy }}
                    <br>
                <button type="submit" class="btn btn-primary float-right">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Blog</title>
</head>
<body>
  <h1>Blog</h1>

  {% for p in posts %}
    <hr>
    <h2>{{ p.title }}</h2>
    <h4>{{ p.created_at }}</h4>
    <p>{{ p.content }}</p>
  {% endfor %}
</body>
</html>

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main_area %}
<div class="row">

<!-- Blog entries-->
<div class="col-lg-8" id="main-area">


    <div id="post-area">
        {% if post.category %}
            <span class="badge badge-info float-right">{{ post.category }}</span>
        {% else %}
            <span class="badge badge-secondary float-right">미분류</span>
        {% endif %}
        <!-- Title-->
        <h2 class="mt-4">{{ post.title }}</h2>
        <h5 class="text-muted">{{ post.hook_text }}</h5>
        <!-- Author-->
        <p class="lead">
            by
            <a href="#!">{{ post.author | upper }}</a>
        </p>
        <hr />

        <!-- 로그인한유저 == 해당포스트의 작성자일 경우, 버튼이 보이도록한다 -->
        {% if user.is_authenticated and user == post.author %}
            <a href="/blog/update_post/{{ post.pk }}" class="btn btn-info btn-sm float-right" role="button"><i class="bi bi-pen-fill"></i> Edit Post</a>
        {% endif %}

        <!-- Date and time-->
        <p>Posted on {{ post.created_at }}</p>
        <hr />
        <!-- Preview image-->
        <!-- <img class="img-fluid rounded" src="https://picsum.photos/id/{{ post.id }}/900/300" alt="..." /> -->
        {% if post.head_image %}
            <img class="img-fluid rounded" src="{{ post.head_image.url }}" alt="{{ post.title }} head_image" />
        {% else %}
            <img class="img-fluid rounded" src="https://picsum.photos/seed/{{ post.id }}/1920/1280" alt="random_image" />
        {% endif %}
        <hr />
        <!-- Post content-->
        <!-- safe : html 태그노출을 방지하는 기능 -->
        <p class="lead">{{ post.content | safe }}</p>
        

        {% if post.tags.exists %}
            <i class="bi bi-tags-fill"></i>
            {% for tag in post.tags.iterator %}
                <a href="{{ tag.get_absolute_url }}"><span class="badge badge-pill badge-light">{{ tag }}</span></a>
            {% endfor %}
            <br>
            <br>
        {% endif %}

        {% if post.file_upload %}
            <!-- <a href="{{ post.file_upload.url }}" class="btn btn-outline-dark" role="button" download>Download<i class="bi bi-filetype-txt"></i></a> -->
            <a href="{{ post.file_upload.url }}" class="btn btn-outline-dark" role="button" download>
                Download:
                {% if post.get_file_ext == 'txt' %}
                    <i class="bi bi-filetype-txt"></i>
                {% elif post.get_file_ext == 'csv' %}
                    <i class="bi bi-filetype-csv"></i>
                {% elif post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
                    <i class="bi bi-file-earmark-spreadsheet"></i>
                {% elif post.get_file_ext == 'docx' or post.get_file_ext == 'doc' %}
                    <i class="bi bi-file-earmark-word"></i>
                {% else %}
                    <i class="bi bi-file-earmark"></i>
                {% endif %}
                {{ post.get_file_name }}
            </a>
        {% endif %}
    </div>

    <hr/>
    <!-- Comments form-->
    <div class="card my-4">
        <h5 class="card-header">Leave a Comment:</h5>
        <div class="card-body">
            {% if user.is_authenticated %}
            <form id="comment-form" method="POST" action="{{ post.get_absolute_url }}new_comment/">
                {% csrf_token %}
                <div class="form-group">{{ comment_form | crispy }}</div>
                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
            {% else %}
                <a href="#" role="button" class="btn btn-outline-dark btn-block btn-sm" data-toggle="modal" data-target="#exampleModal">Log in and leave a comment</a>
            {% endif %}
        </div>
    </div>

    {% if post.comment_set.exists %}
        {% for comment in post.comment_set.iterator %}
        <!-- Single comment-->
        <div class="media mb-4" id="comment-{{ comment.pk }}">
            <img class="d-flex mr-3 rounded-circle" src="https://via.placeholder.com/50x50" alt="..." />
            <div class="media-body">
                {% if user.is_authenticated and comment.author == user %}
                    <div class="float-right">
                    <a href="/blog/update_comment/{{ comment.pk }}/" role="button" class="btn btn-sm btn-info" id="comment-{{ comment.pk }}-update-btn">edit</a>
                    <a href="#" role="button" id="comment-{{ comment.pk }}-delete-modal-btn" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#deleteCommentModal-{{ comment.pk }}">delete</a>
                </div>

                <!-- Modal -->
                <div class="modal fade" id="deleteCommentModal-{{ comment.pk }}" tabindex="-1" role="dialog" aria-labelledby="deleteCommentModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="deleteModalLabel">Are you sure?</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <del>{{ comment | linebreaks }}</del>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                <a href="/blog/delete_comment/{{ comment.pk }}/" role="button" class="btn btn-danger">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>

                {% endif %}
                <h5 class="mt-0">{{ comment.author.username }} &nbsp;&nbsp;<small class="text-muted">{{ comment.created_at }}</small></h5>
                <p>{{ comment.content | linebreaks }}</p>
                {% if comment.created_at != comment.modified_at %}
                    <p class="text-muted float-right"><small>Updated: {{ comment.modified_at }}</small></p>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    {% endif %}
    <hr>
</div>

{% include 'blog/side_widget.html' %}
</div>
{% endblock %}

blog/templates/blog/post_detail_old.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ post.title }} - Blog</title>
</head>
<body>
  <nav>
    <a href="/blog/">Blog</a>
    <a href="/about_me/">About me</a>
  </nav>
<h1>{{ post.title }}</h1>
<h4>{{ post.created_at }}</h4>
<p>{{ post.content }}</p>
<hr>
<h3>여기는 댓글란</h3>
</body>
</html>

blog/templates/blog/post_form.html
{% extends 'base.html' %}

{% block head_title %}Creat Post - Blog{% endblock %}

{% block main_area %}
<div class="row">

    <!-- Blog entries-->
    <div class="col-lg-12" id="main-area">
        <h1>Create New Post</h1>
        <hr>
        <div>
            <form method="post" enctype="multipart/form-data">{% csrf_token %}
                <table>
                    {{ form }}
                    <!-- 템플릿파일에 input추가(태그 입력란) -->
                    <tr>
                        <th><label for="id_tags_str">Tags:</label></th>
                        <td><input type="text" name="tags_str" id="id_tags_str"></td>
                    </tr>
                </table>
                <button type="submit" class="btn btn-primary float-right">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block main_area %}
<div class="row">

<!-- Blog entries-->
<div class="col-lg-8" id="main-area">
<!-- 사용자가 staff이거나 superuser 일때 만 이 버튼이 보이도록 한다 -->
    {% if user.is_authenticated %}
        {% if user.is_superuser or user.is_staff %}
            <a class="btn btn-info btn-sm float-right mt-5" href="/blog/create_post/" role="button">
                <i class="bi bi-pen-fill"></i>&nbsp;&nbsp;New Post
            </a>
        {% endif %}
    {% endif %}

    <h1 class="my-4">
        Blog
        {% if search_info %}<small class="text-muted">{{ search_info }}</small>{% endif %}
        {% if category %}
        <span class="badge badge-secondary">{{ category }}</span>
        {% endif %}
        {% if tag %}
        <span class="badge badge-light"><i class="bi bi-tags-fill"></i>{{ tag }}({{ tag.post_set.count }})</span>
        {% endif %}
    </h1>
    {% if post_list.exists %}
        <!-- Blog post-->
        {% for p in post_list %}
        <div class="card mb-4" id="post-{{ p.pk }}">
            <!-- <img class="card-img-top" src="https://picsum.photos/id/{{ p.id }}/750/200" alt="Card image cap" /> -->
            {% if p.head_image %}
                <img class="card-img-top" src="{{ p.head_image.url }}" alt="{{ p }} head image" />
            {% else %}
                <img class="card-img-top" src="https://picsum.photos/seed/{{ p.id }}/1920/1280" alt="random image" />
            {% endif %}
            <div class="card-body">
                {% if p.category %}
                    <span class="badge badge-info float-right">{{ p.category }}</span>
                {% else %}
                    <span class="badge badge-secondary float-right">미분류</span>
                {% endif %}
                <h5 class="card-title"><a href="{{ p.get_absolute_url }}">{{ p.title }}</a></h5>
                {% if p.hook_text %}
                    <h6 class="text-muted">{{ p.hook_text }}</h6>
                {% endif %}
                <p class="card-text">{{ p.content| truncatewords_html:45 | safe }}</p>

                {% if p.tags.exists %}
                    <i class="bi bi-tags-fill"></i>
                    {% for tag in p.tags.iterator %}
                        <a href="{{ tag.get_absolute_url }}"><span class="badge badge-pill badge-light">{{ tag }}</span></a>
                    {% endfor %}
                    <br>
                    <br>
                {% endif %}
                <a class="btn btn-primary" href="{{ p.get_absolute_url }}">Read More →</a>
            </div>
            <div class="card-footer text-muted">
                {{ p.created_at }}
                <!-- 작성자 들어갈곳 -->
                <a href="#">{{ p.author | upper }}</a>
                <!-- <a href="#!">Start Bootstrap</a> -->
            </div>
        </div>
        {% endfor %}
    {% else %}
        <h2>아직 게시물이 없습니다.</h2>
    {% endif %}



    <!-- Pagination-->
    <!--     
    <ul class="pagination justify-content-center mb-4">
        <li class="page-item"><a class="page-link" href="#!">← Older</a></li>
        <li class="page-item disabled"><a class="page-link" href="#!">Newer →</a></li>
    </ul>
    -->

    <!-- 
        1. 페이지별로 목록보기
        서버쪽에서 목록이 넘어오면, 각페이지별로 목록이 보이도록 하기
        2. 이전페이지 기능
        제일 왼쪽 이전페이지를 클릭을 하면, 이전 페이지로 이동
            - 현재페이지가 1이면, 이전페이지 버튼은 비활성화
        3. 다음페이지 기능
        제일 오른쪽에 다음페이지를 클릭을 하면, 다음 페이지로 이동
            - 현재페이지가 마지막페이지이면, 다음페이지 버튼은 비활성화
    -->

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <!-- 이전페이지 이동 -->
            <!-- 1페이지 일 경우: 비활성화, 1페이지가 아닐 경우: 활성화 -->
            <!-- page_obj.has_previous: 이전 페이지가 있으면 True -->
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="/blog/?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% else %}
            <!-- 이전 페이지가 없는 경우 -->
            <li class="page-item disabled">
                <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% endif %}

            <!-- 페이지별 목록보기 -->
            <!-- views.py의 PostList클래스에 paginate_by = 3 정의를 하면
            템플릿에 넘겨주는 객체 변수
            page_obj.paginator.page_range
            -->

            {% for page in page_obj.paginator.page_range %}
            <!-- page_obj.number : 현재 선택한 페이지 번호-->
                {% if page_obj.number == forloop.counter %}
                <!-- 현재 선택한 페이지 번호는 비활성화 시킴 : 내가 몇번째 페이지에 있는지 -->
                <li class="page-item disabled">
                    <a class="page-link bg-primary text-white" href="{{ request.path }}?page={{ page }}">{{ page }}</a>
                </li>
                {% else %}
                <!-- 선택하지 않은 페이지 번호는 활성화 시킴 -->
                <li class="page-item">
                    <a class="page-link" href="{{ request.path }}?page={{ page }}">{{ page }}</a>
                </li>
                {% endif %}
            {% endfor %}


            <!-- <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li> -->
            
            <!-- 다음페이지로 이동 -->
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="/blog/?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% include 'blog/side_widget.html' %}
</div>
{% endblock %}